export enum ORDER_STATUS {
  DRAFT,
  PENDING,
  WAITING_FOR_PAYMENT,
  WAITING_FOR_PICKUP,
  WAITING_FOR_DELIVERY,
  IN_DELIVERY,
  COMPLETED,
  RETURNED,
  CANCELLED
}

export enum ORDER_PAYMENT_STATUS {
  PENDING,
  WAITING_FOR_PAYMENT,
  PAYMENT_CONFIRMATION,
  PAID,
}
